### ISSUE TITLE
TODO / December ( 2015/12/01~2015/12/31 )

### ISSUE THREAD

**Issue by shosemaru** [shosemaru/Note#1]
# GOAL
⑴ Complete understanding of HTML・CSS
⑵ Mechanism of PDCA / Daily Report・TODO
⑶ Reduce amount of review / 10comment per review
⑷ Raise the speed of typing / Score 300 / E-typing

## TODO / Monthly
- [ ] ⑴ Complete understanding of HTML・CSS
 - [ ] Contribute Qiita / 1 post per week
 - [ ] Read modern coding book / Output LP 
 - [ ] Read textbook of css developing / Output Qiita
 - [ ] Read Bootstrap / All

- [x] ⑵ Mechanism of PDCA
 - [x] Create format of TODO / write in wiki
   - [x] Define goal of TODO
    - [x] Estimate working man-hours
 - [x] Create format of Daily report  / write in wiki
   - [x] Define goal of Daily report 
    - [x] Daily try into a custom
  

- [ ] ⑶ Reduce amount of review / 10comment per review
 - [ ] Mechanism of stock review / Create summarize seats
 - [ ] Mechanism of self_check before review /  Create check lists

- [ ] ⑷ Raise the speed of typing / Score300 (E-typing)
 - [ ] Make daily task / make WBS of 3 weeks

### 1st week（12/1~12/5）
- [x] issue / -
 - [x] Lay monthly plan
 - [x] Lay weekly plan
 - [x] Create TODO format
- [x] Continuous tasks
 - [x] Contribute Qiita
 - [x] Write TODO & Daily Report

### 2nd week (12/7~ 12/12)
- [x] issue / #2
 - [x] Lay weekly plan
 - [x] Create Daily Report format
- [x] Continuous tasks
 - [ ] Contribute Qiita
 - [x] Write TODO & Daily Report
 - [x] write sumary seats
 - [x] Sushida 10000 yen

### 3rd week (12/14~ 12/19)
- [x] issue / #3
 - [x] Lay weekly plan
 - [ ] Read textbook of css design / Output Qiita
- [x] Continuous tasks
 - [ ] Contribute Qiita
 - [x] Write TODO & Daily Report

### 4th week (12/21~ 12/24)
- [x] issue / #4 
 - [ ] Lay weekly plan
- [ ] Continuous tasks
 - [ ] Contribute Qiita
 - [ ] Write TODO & Daily Report
