### ISSUE TITLE
TODO / 2nd week (12/7~ 12/12)

### ISSUE THREAD

**Issue by shosemaru** [shosemaru/Note#2]
# Goal
- [x] Become pro in CSS design
 - [x] Create dev for fi-chat by myself
 - [x] Stock how to create dev and tips of CSS design

## Weekly TODO
- [x] Lay weekly plan
- [x] Create Daily Report format
- [x] Read textbook of css developing / Output Qiita
- [x] Contribute Qiita

## Continuous tasks
 - [x] Write TODO & Daily Report
 - [x] write sumary seats
 - [x] Contribute Qiita
 - [x] Sushida 10000 yen

**Comment by shosemaru** [comment]
Daily Report / 2nd week
Daily-Report  Date  #shosemaru

## Works


## TRY

### Daily TODO
- [x] Diary 

- [x] Typing / Susihida 10000 yen

 
### Weekly TODO
- [ ] Lay weekly plan
- [ ] Qiita 1 contribute
- [ ] CSS design textbook


## Weekly Goal
- [ ] Become pro in CSS design
 - [ ] Create dev for fi-chat by myself
 - [ ] Stock how to create dev and tips of CSS design

## Weekly Task
- [x] Lay weekly plan
- [x] Create Daily Report format
- [ ] Read textbook of css developing / Output Qiita
- [ ] Contribute Qiita

## Continuous tasks
 - [ ] Write TODO & Daily Report
 - [ ] write sumary seats
 - [ ] Sushida 10000 yen

## Learn

**Comment by shosemaru** [comment]
## TODO 12/10

### Attach step_bar & title / all appointment page 
- [ ] PR (2.5h)
 - [ ] Check all page
 - [ ] develop patial layout
 - [ ] Attach step_bar & title
 - [ ] Check & Self review all page

### Change Module css / Confirm impact range 
- [ ] PR (0.5h)
 - [ ] Confirm impact range
 - [ ] Coding
 - [ ] Check & Self review

### Develop layout / Fi-chat
- [ ] PR (1.5h)
 - [ ] develop layout
 - [ ] Compare with surver's
 - [ ] Check & Self review all page

### Develop sidebar / Fi-chat
- [ ] PR (4.5h)
 - [ ] confirm dev
 - [ ] develop sidebar
 - [ ] Compare with surver's
 - [ ] Check & Self review all page

### Industrial physician page / Fix to Review
- [ ] PR (1.5h)
 - [ ] Confirm review
 - [ ] Coding
 - [ ] Check & Self review

**Comment by shosemaru** [comment]
## TODO 12/11

### Industrial physician registration page / Fix to Review
- [ ] PR (1.5h)
 - [ ] Confirm review
 - [ ] Attach title
 - [ ] Redesign layout
 - [ ] Check & Self review

### Attach step_bar & title /  All appointment page 
- [x] PR (1.5h)
 - [x] Use helper
 - [x] Fix logic
 - [x] Check & Self review all page

### Develop layout / Fi-chat
- [ ] PR (1.5h)
 - [ ] develop layout
 - [ ] Compare with surver's
 - [ ] Check & Self review all page

### Develop sidebar / Fi-chat
- [ ] PR (4.5h)
 - [ ] confirm dev
 - [ ] develop sidebar
 - [ ] Compare with servey's
 - [ ] Check & Self review all page

**Comment by shosemaru** [comment]
## TODO 12/12

### Fi-chat / Fix review
- [x] PR (1.5h)
 - [x] Confirm review
 - [x] fix review
 - [x] Check & Self review

### Login page / create front page
- [ ] PR (1.5h)
 - [ ] Coding
 - [ ] Check & Self review

### Develop sidebar / Fi-chat
- [ ] PR (4.5h)
 - [ ] confirm dev
 - [ ] develop sidebar
 - [ ] Compare with servey's
 - [ ] Check & Self review all page

### Develop Header / Fi-chat
- [ ] PR (3.5h)
 - [ ] confirm dev
 - [ ] develop sidebar
 - [ ] Compare with servey's
 - [ ] Check & Self review all page
