### ISSUE TITLE
TODO / 3rd week (12/15~ 12/19)

### ISSUE THREAD

**Issue by shosemaru** [shosemaru/Note#3]
# Goal
- [x] Complete Fi-chat
 - [x] develop Fi-chat's all page

## Weekly TODO
- [x] Lay weekly plan
- [ ] Contribute Qiita

## Continuous tasks
 - [x] Write TODO & Daily Report
 - [x] write sumary seats
 - [ ] Read textbook of CSS design / Output Qiita
 - [ ] Contribute Qiita
 - [ ] Sushida 10000 yen

**Comment by shosemaru** [comment]
# Daily Report (template) / 2nd week

## Works
- [ ] hoge
 - [ ] fuga

## Weekly Goal
- [ ] Become pro in CSS design
 - [ ] Create dev for fi-chat by myself
 - [ ] Stock how to create dev and tips of CSS design

## Weekly Task
- [x] Lay weekly plan
- [x] Create Daily Report format
- [ ] Read textbook of css developing / Output Qiita
- [ ] Contribute Qiita

## Continuous tasks
 - [x] Write TODO & Daily Report
 - [x] write sumary seats
 - [ ] Sushida 10000 yen

## Learn
hogehoge

**Comment by shosemaru** [comment]
### Develop sidebar / Fi-chat
- [x] PR (4.5h)
 - [x] confirm dev
 - [x] develop sidebar
 - [x] Compare with servey's
 - [x] Check & Self review all page

### Develop Header / Fi-chat
- [x] PR (3.5h)
 - [x] confirm dev
 - [x] develop sidebar
 - [x] Compare with servey's
 - [x] Check & Self review all page

**Comment by shosemaru** [comment]
## TODO 12/16

### Fi-chat User list / Front Coding 
- [ ] PR (2h) 10:30~12:30
 - [ ] confirm design
 - [ ] develop sidebar
 - [ ] Compare with servey's
 - [ ] Check & Self review all page

**Comment by shosemaru** [comment]
## TODO 12/16

### Fi-chat User_list page / Fix review
- [x] PR (3h) 
 - [x] list review point
 - [x] fix review
 - [x] Check & Self review all page
 - [ ] write review point list

### Door keeper  / Create log in page
 - [x] confirm dev (3h)
 - [x] design CSS
 - [x] Compare with servey's
 - [x] Check & Self review all page

### Fi-chat User_list page / Fix final review
- [x] PR (1h) 
 - [x] list review point
 - [x] fix review
 - [x] Check & Self review all page
 - [ ] write review point list

### Fi-chat / Create Header 
- [ ] PR (2h)
 - [ ] confirm design
 - [ ] develop Header
 - [ ] Compare with servey's
 - [ ] Check & Self review all page

### Fi-chat  / Create Component
 - [x] confirm design (3h)
 - [x] develop component
 - [x] Compare with servey's
 - [x] Check & Self review all page

**Comment by shosemaru** [comment]
# TODO 12/18

### Fi-chat  / Setting page 1
- [x] PR (3h) 
 - [x] Design component 
 - [x] front coding
 - [x] Check & Self review

### Fi-chat  / Setting page 2
- [x] PR (3h) 
 - [x] Design component 
 - [x] front coding
 - [x] Check & Self review

### Fi-chat  / Setting page 3
- [x] PR (3h) 
 - [x] Design component 
 - [x] front coding
 - [x] Check & Self review

**Comment by shosemaru** [comment]
# TODO 12/18

### Fi-chat  / Self review userlists
- [ ] Merge (0.5h) 
 - [x] Self review 
 - [x] Check & Self review

### Fi-chat  / Self review Settings
- [ ] Merge (1h) 
 - [x] Self review 
 - [x] Check & Self review
 - [x] Fix conflict

### Fi-chat  / Chat page
- [x] PR (4h) 
 - [x] Design component 
 - [x] front coding
 - [x] Check & Self review

### Fi-chat  / FIx review
- [x] PR (2h) 
 - [x] Fix review
 - [x] Check & Self review

### Fi-chat  / All page self review
- [x] Self review (1h) 
 - [x] Check & Self review
