### ISSUE TITLE
TODO / 4th week (12/21~ 12/24)

### ISSUE THREAD

**Issue by shosemaru** [shosemaru/Note#4]
# Goal
- [x] Complete Fi-chat
 - [x] develop Fi-chat's all page
- [ ] Complete Responsive survey
 - [ ] develop SP survey all page

## Weekly TODO
- [ ] Lay weekly plan
- [ ] Contribute Qiita
- [ ] Read textbook of CSS design / Output Qiita

## Continuous tasks
 - [x] Write TODO & Daily Report
 - [x] write sumary seats
 - [ ] Read textbook of CSS design / Output Qiita
 - [ ] Contribute Qiita
 - [ ] Sushida 10000 yen

**Comment by shosemaru** [comment]
## Remainder Task
###  Plan  / Make weekly plan
- [ ] Write weekly goal
 - [ ] Make weekly plan

### Fi-chat  / FIx review
- [ ] Merge (0.5h) 
 - [ ] Fix review
 - [ ] Check & Self review

### Fi-chat  / Move to new Directory
- [ ] PR (1h) 
 - [ ] Fix review
 - [ ] Check & Self review

**Comment by shosemaru** [comment]
## Remainder Task
###  Plan  / Make weekly plan
- [x] Write weekly goal
 - [x] Make weekly plan

### Fi-chat  / FIx review
- [x] Merge (0.5h) 
 - [x] Fix review
 - [x] Check & Self review

### Fi-chat  / Move to new Directory
- [x] PR (1h) 
 - [x] Fix review
 - [x] Check & Self review

**Comment by shosemaru** [comment]
## 12/22 TODO

###  Plan  / Make weekly plan
- [x] Write weekly goal
 - [x] Make weekly plan

### First_login (Opa / User) / Make responsive
- [ ] PR
 - [ ] Coding
 - [ ] Check & Self review

### Login / Make responsive
- [ ] PR
 - [ ] Coding
 - [ ] Check & Self review

### Fi-chat  / FIx review
- [x] Merge 
 - [x] Fix review
 - [x] Check & Self review

### Push Designer  / Get Specification
- [x] Get Specification
 - [x] Push designer

**Comment by shosemaru** [comment]
## 12/23 TODO

###  Login・Setting page / Finish all
- [x] Merge (1h)
 - [x] Fix review
 - [x] Check & Self review

### Basic info setting  / Make responsive
- [x] PR (2h)
 - [x] Coding
 - [x] Check & Self review

### Section start page ⑴  / Make responsive
- [x] PR (2h)
 - [x] Coding
 - [x] Check & Self review

### Section start page ⑵  / Make responsive
- [x] PR (0.5h)
 - [x] Coding
 - [x] Check & Self review

### Step list page  / Make responsive
- [x] PR (2h)
 - [x] Coding
 - [x] Check & Self review

**Comment by shosemaru** [comment]
## 12/24 TODO

### Basic info setting  / Final control
- [x] PR (0.5h) 10:30~11:00
 - [x] Coding
 - [x] Check & Self review

### Section start page ⑴  / Fix review
- [x] PR (1h) 11:00~12:00
 - [x] Coding
 - [ ] Check & Self review

### Section start page ⑵  / Use component
- [x] PR (1h)12:00~13:00
 - [x] Coding
 - [ ] Check & Self review

### Absenteeisum and Presenteeisum page   / Make responsive
- [x] PR (3h)14:00~17:00
 - [x] Coding
 - [x] Check & Self review


### Wellness survey  / Add new logo
- [x] PR (0.5h)17:30~18:00
 - [x] Add img
 - [x] Check & Self review


### Fi-chat  / Fix my dept
- [x] PR (1h)18:00~19:00
 - [x] Coding
 - [x] Check & Self review

### Absenteeisum and Presenteeisum page   / Fix review
- [x] PR (1.5h)19:00~20:30
 - [x] Coding
 - [x] Check & Self review
